export default `
<graphol version="3">
  <project name="TEST" version="1.0">
    <ontology prefix="t" iri="http://www.obdasystems.com/test" lang="en" addLabelFromUserInput="0" addLabelFromSimpleName="0">
      <prefixes>
        <prefix>
          <value>xsd</value>
          <namespace>http://www.w3.org/2001/XMLSchema#</namespace>
        </prefix>
        <prefix>
          <value>rdf</value>
          <namespace>http://www.w3.org/1999/02/22-rdf-syntax-ns#</namespace>
        </prefix>
        <prefix>
          <value>rdfs</value>
          <namespace>http://www.w3.org/2000/01/rdf-schema#</namespace>
        </prefix>
        <prefix>
          <value>test</value>
          <namespace>http://www.obdasystems.com/test</namespace>
        </prefix>
        <prefix>
          <value></value>
          <namespace>http://www.obdasystems.com/</namespace>
        </prefix>
        <prefix>
          <value>test2</value>
          <namespace>http://www.obdasystems.com/test</namespace>
        </prefix>
      </prefixes>
      <languages>
        <language>it</language>
        <language>en</language>
      </languages>
      <iris>
        <iri>
          <value>http://www.obdasystems.com/testNode1</value>
          <annotations>
            <annotation>
              <subject>http://www.obdasystems.com/testNode1</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#label</property>
              <object>
                <lexicalForm>label con ritorni
a capo senza lingua</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language/>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/testNode1</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#label</property>
              <object>
                <lexicalForm>label2 senza lingua</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language/>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/testNode1</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#label</property>
              <object>
                <lexicalForm>label inglese</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/testNode1</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#label</property>
              <object>
                <lexicalForm>label inglese 2</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
          </annotations>
          <functional>0</functional>
          <inverseFunctional/>
          <symmetric>1</symmetric>
          <asymmetric/>
          <reflexive/>
          <irreflexive/>
          <transitive/>
        </iri>
        <iri>
          <value>http://www.obdasystems.com/test</value>
          <annotations>
            <annotation>
              <subject>http://www.obdasystems.com/test/</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#comment</property>
              <object>
                <lexicalForm>Ontology for testing</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/test/</subject>
              <property>http://www.w3.org/2000/01/rdf-schema#comment</property>
              <object>
                <lexicalForm>Hello world</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/test/</subject>
              <property>http://www.obdasystems.com/test/author</property>
              <object>
                <lexicalForm>obdasystems</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
            <annotation>
              <subject>http://www.obdasystems.com/test/</subject>
              <property>http://www.obdasystems.com/test/author</property>
              <object>
                <lexicalForm>secondauthor</lexicalForm>
                <datatype>http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral</datatype>
                <language>en</language>
              </object>
            </annotation>
          </annotations>
        </iri>
      </iris>
    </ontology>
  </project>
</graphol>
`