/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionUser
 */
export interface ActionUser {
    /**
     * 
     * @type {string}
     * @memberof ActionUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActionUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ActionUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ActionUser
     */
    email?: string;
}

/**
 * Check if a given object implements the ActionUser interface.
 */
export function instanceOfActionUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ActionUserFromJSON(json: any): ActionUser {
    return ActionUserFromJSONTyped(json, false);
}

export function ActionUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ActionUserToJSON(value?: ActionUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
    };
}

