/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionInvolvedElements } from './ActionInvolvedElements';
import {
    ActionInvolvedElementsFromJSON,
    ActionInvolvedElementsFromJSONTyped,
    ActionInvolvedElementsToJSON,
} from './ActionInvolvedElements';
import type { ActionUser } from './ActionUser';
import {
    ActionUserFromJSON,
    ActionUserFromJSONTyped,
    ActionUserToJSON,
} from './ActionUser';

/**
 * Actions describes what user has done on a single element or element's metadata. The user can add, edit or remove something. The "something" is described by the operation involved in the action, it can be an operation over an entity, a diagram, a hierarchy and so on.
 * Reverting an action means reverting the operation that has been done and it depends on the type of the action. - Add => Remove - Remove => Add - Edit => restore the previous state of the subject of the operation made
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    operationType: ActionOperationTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof Action
     */
    subject: object;
    /**
     * 
     * @type {object}
     * @memberof Action
     */
    previousState?: object;
    /**
     * 
     * @type {ActionInvolvedElements}
     * @memberof Action
     */
    involvedElements?: ActionInvolvedElements;
    /**
     * 
     * @type {Array<Action>}
     * @memberof Action
     */
    subactions?: Array<Action>;
    /**
     * 
     * @type {ActionUser}
     * @memberof Action
     */
    user: ActionUser;
    /**
     * 
     * @type {number}
     * @memberof Action
     */
    timestamp: number;
}

/**
* @export
* @enum {string}
*/
export enum ActionOperationTypeEnum {
    ADD = 'add',
    EDIT = 'edit',
    REMOVE = 'remove'
}


/**
 * Check if a given object implements the Action interface.
 */
export function instanceOfAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "operationType" in value;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function ActionFromJSON(json: any): Action {
    return ActionFromJSONTyped(json, false);
}

export function ActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Action {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'operationType': json['operationType'],
        'subject': json['subject'],
        'previousState': !exists(json, 'previousState') ? undefined : json['previousState'],
        'involvedElements': !exists(json, 'involvedElements') ? undefined : ActionInvolvedElementsFromJSON(json['involvedElements']),
        'subactions': !exists(json, 'subactions') ? undefined : ((json['subactions'] as Array<any>).map(ActionFromJSON)),
        'user': ActionUserFromJSON(json['user']),
        'timestamp': json['timestamp'],
    };
}

export function ActionToJSON(value?: Action | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'operationType': value.operationType,
        'subject': value.subject,
        'previousState': value.previousState,
        'involvedElements': ActionInvolvedElementsToJSON(value.involvedElements),
        'subactions': value.subactions === undefined ? undefined : ((value.subactions as Array<any>).map(ActionToJSON)),
        'user': ActionUserToJSON(value.user),
        'timestamp': value.timestamp,
    };
}

