/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Annotation
 */
export interface Annotation {
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof Annotation
     */
    hasIriValue?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    property: string;
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof Annotation
     */
    datatype?: string;
}

/**
 * Check if a given object implements the Annotation interface.
 */
export function instanceOfAnnotation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "property" in value;

    return isInstance;
}

export function AnnotationFromJSON(json: any): Annotation {
    return AnnotationFromJSONTyped(json, false);
}

export function AnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Annotation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'hasIriValue': !exists(json, 'hasIriValue') ? undefined : json['hasIriValue'],
        'property': json['property'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'datatype': !exists(json, 'datatype') ? undefined : json['datatype'],
    };
}

export function AnnotationToJSON(value?: Annotation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'hasIriValue': value.hasIriValue,
        'property': value.property,
        'language': value.language,
        'datatype': value.datatype,
    };
}

