/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataPropertyValue } from './DataPropertyValue';
import {
    DataPropertyValueFromJSON,
    DataPropertyValueFromJSONTyped,
    DataPropertyValueToJSON,
} from './DataPropertyValue';

/**
 * 
 * @export
 * @interface ClassInstanceEntityAllOf
 */
export interface ClassInstanceEntityAllOf {
    /**
     * 
     * @type {Array<string>}
     * @memberof ClassInstanceEntityAllOf
     */
    parentClasses?: Array<string>;
    /**
     * 
     * @type {Array<DataPropertyValue>}
     * @memberof ClassInstanceEntityAllOf
     */
    dataProperties?: Array<DataPropertyValue>;
    /**
     * 
     * @type {string}
     * @memberof ClassInstanceEntityAllOf
     */
    shortIri?: string;
}

/**
 * Check if a given object implements the ClassInstanceEntityAllOf interface.
 */
export function instanceOfClassInstanceEntityAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClassInstanceEntityAllOfFromJSON(json: any): ClassInstanceEntityAllOf {
    return ClassInstanceEntityAllOfFromJSONTyped(json, false);
}

export function ClassInstanceEntityAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassInstanceEntityAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentClasses': !exists(json, 'parentClasses') ? undefined : json['parentClasses'],
        'dataProperties': !exists(json, 'dataProperties') ? undefined : ((json['dataProperties'] as Array<any>).map(DataPropertyValueFromJSON)),
        'shortIri': !exists(json, 'shortIri') ? undefined : json['shortIri'],
    };
}

export function ClassInstanceEntityAllOfToJSON(value?: ClassInstanceEntityAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parentClasses': value.parentClasses,
        'dataProperties': value.dataProperties === undefined ? undefined : ((value.dataProperties as Array<any>).map(DataPropertyValueToJSON)),
        'shortIri': value.shortIri,
    };
}

