/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomNodeRenderingInstanceNodesColorAllOfScale } from './CustomNodeRenderingInstanceNodesColorAllOfScale';
import {
    CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSON,
    CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSONTyped,
    CustomNodeRenderingInstanceNodesColorAllOfScaleToJSON,
} from './CustomNodeRenderingInstanceNodesColorAllOfScale';

/**
 * 
 * @export
 * @interface CustomNodeRenderingInstanceNodesColorAllOf
 */
export interface CustomNodeRenderingInstanceNodesColorAllOf {
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesColorAllOf
     */
    aggregation?: string;
    /**
     * 
     * @type {CustomNodeRenderingInstanceNodesColorAllOfScale}
     * @memberof CustomNodeRenderingInstanceNodesColorAllOf
     */
    scale?: CustomNodeRenderingInstanceNodesColorAllOfScale;
}

/**
 * Check if a given object implements the CustomNodeRenderingInstanceNodesColorAllOf interface.
 */
export function instanceOfCustomNodeRenderingInstanceNodesColorAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomNodeRenderingInstanceNodesColorAllOfFromJSON(json: any): CustomNodeRenderingInstanceNodesColorAllOf {
    return CustomNodeRenderingInstanceNodesColorAllOfFromJSONTyped(json, false);
}

export function CustomNodeRenderingInstanceNodesColorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRenderingInstanceNodesColorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aggregation': !exists(json, 'aggregation') ? undefined : json['aggregation'],
        'scale': !exists(json, 'scale') ? undefined : CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSON(json['scale']),
    };
}

export function CustomNodeRenderingInstanceNodesColorAllOfToJSON(value?: CustomNodeRenderingInstanceNodesColorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aggregation': value.aggregation,
        'scale': CustomNodeRenderingInstanceNodesColorAllOfScaleToJSON(value.scale),
    };
}

