/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomNodeRenderingInstanceNodesSizeAllOf
 */
export interface CustomNodeRenderingInstanceNodesSizeAllOf {
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesSizeAllOf
     */
    aggregation?: string;
}

/**
 * Check if a given object implements the CustomNodeRenderingInstanceNodesSizeAllOf interface.
 */
export function instanceOfCustomNodeRenderingInstanceNodesSizeAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomNodeRenderingInstanceNodesSizeAllOfFromJSON(json: any): CustomNodeRenderingInstanceNodesSizeAllOf {
    return CustomNodeRenderingInstanceNodesSizeAllOfFromJSONTyped(json, false);
}

export function CustomNodeRenderingInstanceNodesSizeAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRenderingInstanceNodesSizeAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aggregation': !exists(json, 'aggregation') ? undefined : json['aggregation'],
    };
}

export function CustomNodeRenderingInstanceNodesSizeAllOfToJSON(value?: CustomNodeRenderingInstanceNodesSizeAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aggregation': value.aggregation,
    };
}

