/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomNodeRenderingInstanceNodesColorAllOfScale } from './CustomNodeRenderingInstanceNodesColorAllOfScale';
import {
    CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSON,
    CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSONTyped,
    CustomNodeRenderingInstanceNodesColorAllOfScaleToJSON,
} from './CustomNodeRenderingInstanceNodesColorAllOfScale';
import type { OntologyPath } from './OntologyPath';
import {
    OntologyPathFromJSON,
    OntologyPathFromJSONTyped,
    OntologyPathToJSON,
} from './OntologyPath';

/**
 * 
 * @export
 * @interface CustomNodeRenderingInstanceNodesColor
 */
export interface CustomNodeRenderingInstanceNodesColor {
    /**
     * 
     * @type {boolean}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    inherited?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    dataPropertyIri?: string;
    /**
     * 
     * @type {OntologyPath}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    pathToDataProperty?: OntologyPath;
    /**
     * 
     * @type {boolean}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    log?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    aggregation?: string;
    /**
     * 
     * @type {CustomNodeRenderingInstanceNodesColorAllOfScale}
     * @memberof CustomNodeRenderingInstanceNodesColor
     */
    scale?: CustomNodeRenderingInstanceNodesColorAllOfScale;
}

/**
 * Check if a given object implements the CustomNodeRenderingInstanceNodesColor interface.
 */
export function instanceOfCustomNodeRenderingInstanceNodesColor(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomNodeRenderingInstanceNodesColorFromJSON(json: any): CustomNodeRenderingInstanceNodesColor {
    return CustomNodeRenderingInstanceNodesColorFromJSONTyped(json, false);
}

export function CustomNodeRenderingInstanceNodesColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRenderingInstanceNodesColor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inherited': !exists(json, 'inherited') ? undefined : json['inherited'],
        'dataPropertyIri': !exists(json, 'dataPropertyIri') ? undefined : json['dataPropertyIri'],
        'pathToDataProperty': !exists(json, 'pathToDataProperty') ? undefined : OntologyPathFromJSON(json['pathToDataProperty']),
        'log': !exists(json, 'log') ? undefined : json['log'],
        'aggregation': !exists(json, 'aggregation') ? undefined : json['aggregation'],
        'scale': !exists(json, 'scale') ? undefined : CustomNodeRenderingInstanceNodesColorAllOfScaleFromJSON(json['scale']),
    };
}

export function CustomNodeRenderingInstanceNodesColorToJSON(value?: CustomNodeRenderingInstanceNodesColor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inherited': value.inherited,
        'dataPropertyIri': value.dataPropertyIri,
        'pathToDataProperty': OntologyPathToJSON(value.pathToDataProperty),
        'log': value.log,
        'aggregation': value.aggregation,
        'scale': CustomNodeRenderingInstanceNodesColorAllOfScaleToJSON(value.scale),
    };
}

