/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomNodeRenderingInstanceNodesCoordinates
 */
export interface CustomNodeRenderingInstanceNodesCoordinates {
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesCoordinates
     */
    dataPropertyIriX: string;
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesCoordinates
     */
    dataPropertyIriY: string;
}

/**
 * Check if a given object implements the CustomNodeRenderingInstanceNodesCoordinates interface.
 */
export function instanceOfCustomNodeRenderingInstanceNodesCoordinates(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dataPropertyIriX" in value;
    isInstance = isInstance && "dataPropertyIriY" in value;

    return isInstance;
}

export function CustomNodeRenderingInstanceNodesCoordinatesFromJSON(json: any): CustomNodeRenderingInstanceNodesCoordinates {
    return CustomNodeRenderingInstanceNodesCoordinatesFromJSONTyped(json, false);
}

export function CustomNodeRenderingInstanceNodesCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRenderingInstanceNodesCoordinates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataPropertyIriX': json['dataPropertyIriX'],
        'dataPropertyIriY': json['dataPropertyIriY'],
    };
}

export function CustomNodeRenderingInstanceNodesCoordinatesToJSON(value?: CustomNodeRenderingInstanceNodesCoordinates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataPropertyIriX': value.dataPropertyIriX,
        'dataPropertyIriY': value.dataPropertyIriY,
    };
}

