/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OntologyPath } from './OntologyPath';
import {
    OntologyPathFromJSON,
    OntologyPathFromJSONTyped,
    OntologyPathToJSON,
} from './OntologyPath';

/**
 * 
 * @export
 * @interface CustomNodeRenderingInstanceNodesSize
 */
export interface CustomNodeRenderingInstanceNodesSize {
    /**
     * 
     * @type {boolean}
     * @memberof CustomNodeRenderingInstanceNodesSize
     */
    inherited?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesSize
     */
    dataPropertyIri?: string;
    /**
     * 
     * @type {OntologyPath}
     * @memberof CustomNodeRenderingInstanceNodesSize
     */
    pathToDataProperty?: OntologyPath;
    /**
     * 
     * @type {boolean}
     * @memberof CustomNodeRenderingInstanceNodesSize
     */
    log?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomNodeRenderingInstanceNodesSize
     */
    aggregation?: string;
}

/**
 * Check if a given object implements the CustomNodeRenderingInstanceNodesSize interface.
 */
export function instanceOfCustomNodeRenderingInstanceNodesSize(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomNodeRenderingInstanceNodesSizeFromJSON(json: any): CustomNodeRenderingInstanceNodesSize {
    return CustomNodeRenderingInstanceNodesSizeFromJSONTyped(json, false);
}

export function CustomNodeRenderingInstanceNodesSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRenderingInstanceNodesSize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inherited': !exists(json, 'inherited') ? undefined : json['inherited'],
        'dataPropertyIri': !exists(json, 'dataPropertyIri') ? undefined : json['dataPropertyIri'],
        'pathToDataProperty': !exists(json, 'pathToDataProperty') ? undefined : OntologyPathFromJSON(json['pathToDataProperty']),
        'log': !exists(json, 'log') ? undefined : json['log'],
        'aggregation': !exists(json, 'aggregation') ? undefined : json['aggregation'],
    };
}

export function CustomNodeRenderingInstanceNodesSizeToJSON(value?: CustomNodeRenderingInstanceNodesSize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inherited': value.inherited,
        'dataPropertyIri': value.dataPropertyIri,
        'pathToDataProperty': OntologyPathToJSON(value.pathToDataProperty),
        'log': value.log,
        'aggregation': value.aggregation,
    };
}

