/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomNodeRenderingClassNodes } from './CustomNodeRenderingClassNodes';
import {
    CustomNodeRenderingClassNodesFromJSON,
    CustomNodeRenderingClassNodesFromJSONTyped,
    CustomNodeRenderingClassNodesToJSON,
} from './CustomNodeRenderingClassNodes';
import type { CustomNodeRenderingInstanceNodes } from './CustomNodeRenderingInstanceNodes';
import {
    CustomNodeRenderingInstanceNodesFromJSON,
    CustomNodeRenderingInstanceNodesFromJSONTyped,
    CustomNodeRenderingInstanceNodesToJSON,
} from './CustomNodeRenderingInstanceNodes';

/**
 * 
 * @export
 * @interface CustomNodeRendering
 */
export interface CustomNodeRendering {
    /**
     * 
     * @type {CustomNodeRenderingClassNodes}
     * @memberof CustomNodeRendering
     */
    classNodes?: CustomNodeRenderingClassNodes;
    /**
     * 
     * @type {CustomNodeRenderingInstanceNodes}
     * @memberof CustomNodeRendering
     */
    instanceNodes?: CustomNodeRenderingInstanceNodes;
}

/**
 * Check if a given object implements the CustomNodeRendering interface.
 */
export function instanceOfCustomNodeRendering(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomNodeRenderingFromJSON(json: any): CustomNodeRendering {
    return CustomNodeRenderingFromJSONTyped(json, false);
}

export function CustomNodeRenderingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomNodeRendering {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classNodes': !exists(json, 'classNodes') ? undefined : CustomNodeRenderingClassNodesFromJSON(json['classNodes']),
        'instanceNodes': !exists(json, 'instanceNodes') ? undefined : CustomNodeRenderingInstanceNodesFromJSON(json['instanceNodes']),
    };
}

export function CustomNodeRenderingToJSON(value?: CustomNodeRendering | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classNodes': CustomNodeRenderingClassNodesToJSON(value.classNodes),
        'instanceNodes': CustomNodeRenderingInstanceNodesToJSON(value.instanceNodes),
    };
}

