/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Diagram } from './Diagram';
import {
    DiagramFromJSON,
    DiagramFromJSONTyped,
    DiagramToJSON,
} from './Diagram';

/**
 * 
 * @export
 * @interface DiagramOp
 */
export interface DiagramOp {
    /**
     * 
     * @type {Diagram}
     * @memberof DiagramOp
     */
    subject: Diagram;
    /**
     * 
     * @type {Diagram}
     * @memberof DiagramOp
     */
    previousState?: Diagram;
}

/**
 * Check if a given object implements the DiagramOp interface.
 */
export function instanceOfDiagramOp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subject" in value;

    return isInstance;
}

export function DiagramOpFromJSON(json: any): DiagramOp {
    return DiagramOpFromJSONTyped(json, false);
}

export function DiagramOpFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagramOp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': DiagramFromJSON(json['subject']),
        'previousState': !exists(json, 'previousState') ? undefined : DiagramFromJSON(json['previousState']),
    };
}

export function DiagramOpToJSON(value?: DiagramOp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': DiagramToJSON(value.subject),
        'previousState': DiagramToJSON(value.previousState),
    };
}

