/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';
import type { TypesEnum } from './TypesEnum';
import {
    TypesEnumFromJSON,
    TypesEnumFromJSONTyped,
    TypesEnumToJSON,
} from './TypesEnum';

/**
 * 
 * @export
 * @interface Edge
 */
export interface Edge {
    /**
     * 
     * @type {string}
     * @memberof Edge
     */
    id: string;
    /**
     * In case of replicated elements, this is the ID of the original element replicated in multiple occurrences, all of them with different IDs
     * @type {string}
     * @memberof Edge
     */
    originalId?: string;
    /**
     * 
     * @type {number}
     * @memberof Edge
     */
    diagramId?: number;
    /**
     * 
     * @type {string}
     * @memberof Edge
     */
    displayedName?: string;
    /**
     * 
     * @type {string}
     * @memberof Edge
     */
    iri?: string;
    /**
     * 
     * @type {TypesEnum}
     * @memberof Edge
     */
    type: TypesEnum;
    /**
     * 
     * @type {string}
     * @memberof Edge
     */
    sourceId: string;
    /**
     * 
     * @type {string}
     * @memberof Edge
     */
    targetId: string;
    /**
     * 
     * @type {Array<Position>}
     * @memberof Edge
     */
    breakpoints?: Array<Position>;
    /**
     * 
     * @type {boolean}
     * @memberof Edge
     */
    domainTyped?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Edge
     */
    rangeTyped?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Edge
     */
    domainMandatory?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Edge
     */
    rangeMandatory?: boolean;
}

/**
 * Check if a given object implements the Edge interface.
 */
export function instanceOfEdge(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "sourceId" in value;
    isInstance = isInstance && "targetId" in value;

    return isInstance;
}

export function EdgeFromJSON(json: any): Edge {
    return EdgeFromJSONTyped(json, false);
}

export function EdgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Edge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'originalId': !exists(json, 'originalId') ? undefined : json['originalId'],
        'diagramId': !exists(json, 'diagramId') ? undefined : json['diagramId'],
        'displayedName': !exists(json, 'displayedName') ? undefined : json['displayedName'],
        'iri': !exists(json, 'iri') ? undefined : json['iri'],
        'type': TypesEnumFromJSON(json['type']),
        'sourceId': json['sourceId'],
        'targetId': json['targetId'],
        'breakpoints': !exists(json, 'breakpoints') ? undefined : ((json['breakpoints'] as Array<any>).map(PositionFromJSON)),
        'domainTyped': !exists(json, 'domainTyped') ? undefined : json['domainTyped'],
        'rangeTyped': !exists(json, 'rangeTyped') ? undefined : json['rangeTyped'],
        'domainMandatory': !exists(json, 'domainMandatory') ? undefined : json['domainMandatory'],
        'rangeMandatory': !exists(json, 'rangeMandatory') ? undefined : json['rangeMandatory'],
    };
}

export function EdgeToJSON(value?: Edge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'originalId': value.originalId,
        'diagramId': value.diagramId,
        'displayedName': value.displayedName,
        'iri': value.iri,
        'type': TypesEnumToJSON(value.type),
        'sourceId': value.sourceId,
        'targetId': value.targetId,
        'breakpoints': value.breakpoints === undefined ? undefined : ((value.breakpoints as Array<any>).map(PositionToJSON)),
        'domainTyped': value.domainTyped,
        'rangeTyped': value.rangeTyped,
        'domainMandatory': value.domainMandatory,
        'rangeMandatory': value.rangeMandatory,
    };
}

