/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementAiGenerated
 */
export interface ElementAiGenerated {
    /**
     * 
     * @type {string}
     * @memberof ElementAiGenerated
     */
    chunkId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ElementAiGenerated
     */
    isNew?: boolean;
}

/**
 * Check if a given object implements the ElementAiGenerated interface.
 */
export function instanceOfElementAiGenerated(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkId" in value;

    return isInstance;
}

export function ElementAiGeneratedFromJSON(json: any): ElementAiGenerated {
    return ElementAiGeneratedFromJSONTyped(json, false);
}

export function ElementAiGeneratedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementAiGenerated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chunkId': json['chunkId'],
        'isNew': !exists(json, 'isNew') ? undefined : json['isNew'],
    };
}

export function ElementAiGeneratedToJSON(value?: ElementAiGenerated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chunkId': value.chunkId,
        'isNew': value.isNew,
    };
}

