/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum FunctionPropertiesEnum {
    FUNCTIONAL = 'functional',
    INVERSE_FUNCTIONAL = 'inverseFunctional',
    TRANSITIVE = 'transitive',
    SYMMETRIC = 'symmetric',
    ASYMMETRIC = 'asymmetric',
    REFLEXIVE = 'reflexive',
    IRREFLEXIVE = 'irreflexive'
}


export function FunctionPropertiesEnumFromJSON(json: any): FunctionPropertiesEnum {
    return FunctionPropertiesEnumFromJSONTyped(json, false);
}

export function FunctionPropertiesEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionPropertiesEnum {
    return json as FunctionPropertiesEnum;
}

export function FunctionPropertiesEnumToJSON(value?: FunctionPropertiesEnum | null): any {
    return value as any;
}

