/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceShortestPathSource
 */
export interface InstanceShortestPathSource {
    /**
     * 
     * @type {string}
     * @memberof InstanceShortestPathSource
     */
    instanceIRI: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceShortestPathSource
     */
    parentClasses: Array<string>;
}

/**
 * Check if a given object implements the InstanceShortestPathSource interface.
 */
export function instanceOfInstanceShortestPathSource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "instanceIRI" in value;
    isInstance = isInstance && "parentClasses" in value;

    return isInstance;
}

export function InstanceShortestPathSourceFromJSON(json: any): InstanceShortestPathSource {
    return InstanceShortestPathSourceFromJSONTyped(json, false);
}

export function InstanceShortestPathSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceShortestPathSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceIRI': json['instanceIRI'],
        'parentClasses': json['parentClasses'],
    };
}

export function InstanceShortestPathSourceToJSON(value?: InstanceShortestPathSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instanceIRI': value.instanceIRI,
        'parentClasses': value.parentClasses,
    };
}

