/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceFilterProperty } from './InstanceFilterProperty';
import {
    InstanceFilterPropertyFromJSON,
    InstanceFilterPropertyFromJSONTyped,
    InstanceFilterPropertyToJSON,
} from './InstanceFilterProperty';

/**
 * 
 * @export
 * @interface InstanceFilter
 */
export interface InstanceFilter {
    /**
     * 
     * @type {string}
     * @memberof InstanceFilter
     */
    operator: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstanceFilter
     */
    valid?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceFilter
     */
    values: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InstanceFilter
     */
    rangeClasses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InstanceFilter
     */
    rangeDataProperty?: string;
    /**
     * 
     * @type {InstanceFilterProperty}
     * @memberof InstanceFilter
     */
    property: InstanceFilterProperty;
}

/**
 * Check if a given object implements the InstanceFilter interface.
 */
export function instanceOfInstanceFilter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "operator" in value;
    isInstance = isInstance && "values" in value;
    isInstance = isInstance && "property" in value;

    return isInstance;
}

export function InstanceFilterFromJSON(json: any): InstanceFilter {
    return InstanceFilterFromJSONTyped(json, false);
}

export function InstanceFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'operator': json['operator'],
        'valid': !exists(json, 'valid') ? undefined : json['valid'],
        'values': json['values'],
        'rangeClasses': !exists(json, 'rangeClasses') ? undefined : json['rangeClasses'],
        'rangeDataProperty': !exists(json, 'rangeDataProperty') ? undefined : json['rangeDataProperty'],
        'property': InstanceFilterPropertyFromJSON(json['property']),
    };
}

export function InstanceFilterToJSON(value?: InstanceFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'operator': value.operator,
        'valid': value.valid,
        'values': value.values,
        'rangeClasses': value.rangeClasses,
        'rangeDataProperty': value.rangeDataProperty,
        'property': InstanceFilterPropertyToJSON(value.property),
    };
}

