/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TypesEnum } from './TypesEnum';
import {
    TypesEnumFromJSON,
    TypesEnumFromJSONTyped,
    TypesEnumToJSON,
} from './TypesEnum';

/**
 * 
 * @export
 * @interface InstanceFilterProperty
 */
export interface InstanceFilterProperty {
    /**
     * 
     * @type {string}
     * @memberof InstanceFilterProperty
     */
    iri?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstanceFilterProperty
     */
    direct?: boolean;
    /**
     * 
     * @type {TypesEnum}
     * @memberof InstanceFilterProperty
     */
    type?: TypesEnum;
}

/**
 * Check if a given object implements the InstanceFilterProperty interface.
 */
export function instanceOfInstanceFilterProperty(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InstanceFilterPropertyFromJSON(json: any): InstanceFilterProperty {
    return InstanceFilterPropertyFromJSONTyped(json, false);
}

export function InstanceFilterPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceFilterProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iri': !exists(json, 'iri') ? undefined : json['iri'],
        'direct': !exists(json, 'direct') ? undefined : json['direct'],
        'type': !exists(json, 'type') ? undefined : TypesEnumFromJSON(json['type']),
    };
}

export function InstanceFilterPropertyToJSON(value?: InstanceFilterProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'iri': value.iri,
        'direct': value.direct,
        'type': TypesEnumToJSON(value.type),
    };
}

