/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Action } from './Action';
import {
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './Action';
import type { ActionInvolvedElements } from './ActionInvolvedElements';
import {
    ActionInvolvedElementsFromJSON,
    ActionInvolvedElementsFromJSONTyped,
    ActionInvolvedElementsToJSON,
} from './ActionInvolvedElements';
import type { ActionUser } from './ActionUser';
import {
    ActionUserFromJSON,
    ActionUserFromJSONTyped,
    ActionUserToJSON,
} from './ActionUser';
import type { Namespace } from './Namespace';
import {
    NamespaceFromJSON,
    NamespaceFromJSONTyped,
    NamespaceToJSON,
} from './Namespace';

/**
 * 
 * @export
 * @interface NamespaceAction
 */
export interface NamespaceAction {
    /**
     * 
     * @type {Namespace}
     * @memberof NamespaceAction
     */
    subject: Namespace;
    /**
     * 
     * @type {Namespace}
     * @memberof NamespaceAction
     */
    previousState?: Namespace;
    /**
     * 
     * @type {string}
     * @memberof NamespaceAction
     */
    operationType: NamespaceActionOperationTypeEnum;
    /**
     * 
     * @type {ActionInvolvedElements}
     * @memberof NamespaceAction
     */
    involvedElements?: ActionInvolvedElements;
    /**
     * 
     * @type {Array<Action>}
     * @memberof NamespaceAction
     */
    subactions?: Array<Action>;
    /**
     * 
     * @type {ActionUser}
     * @memberof NamespaceAction
     */
    user: ActionUser;
    /**
     * 
     * @type {number}
     * @memberof NamespaceAction
     */
    timestamp: number;
}

/**
* @export
* @enum {string}
*/
export enum NamespaceActionOperationTypeEnum {
    ADD = 'add',
    EDIT = 'edit',
    REMOVE = 'remove'
}


/**
 * Check if a given object implements the NamespaceAction interface.
 */
export function instanceOfNamespaceAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "operationType" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function NamespaceActionFromJSON(json: any): NamespaceAction {
    return NamespaceActionFromJSONTyped(json, false);
}

export function NamespaceActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': NamespaceFromJSON(json['subject']),
        'previousState': !exists(json, 'previousState') ? undefined : NamespaceFromJSON(json['previousState']),
        'operationType': json['operationType'],
        'involvedElements': !exists(json, 'involvedElements') ? undefined : ActionInvolvedElementsFromJSON(json['involvedElements']),
        'subactions': !exists(json, 'subactions') ? undefined : ((json['subactions'] as Array<any>).map(ActionFromJSON)),
        'user': ActionUserFromJSON(json['user']),
        'timestamp': json['timestamp'],
    };
}

export function NamespaceActionToJSON(value?: NamespaceAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': NamespaceToJSON(value.subject),
        'previousState': NamespaceToJSON(value.previousState),
        'operationType': value.operationType,
        'involvedElements': ActionInvolvedElementsToJSON(value.involvedElements),
        'subactions': value.subactions === undefined ? undefined : ((value.subactions as Array<any>).map(ActionToJSON)),
        'user': ActionUserToJSON(value.user),
        'timestamp': value.timestamp,
    };
}

