/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ElementAiGenerated } from './ElementAiGenerated';
import {
    ElementAiGeneratedFromJSON,
    ElementAiGeneratedFromJSONTyped,
    ElementAiGeneratedToJSON,
} from './ElementAiGenerated';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';
import type { TypesEnum } from './TypesEnum';
import {
    TypesEnumFromJSON,
    TypesEnumFromJSONTyped,
    TypesEnumToJSON,
} from './TypesEnum';

/**
 * 
 * @export
 * @interface Node
 */
export interface Node {
    /**
     * 
     * @type {string}
     * @memberof Node
     */
    id: string;
    /**
     * In case of replicated elements, this is the ID of the original element replicated in multiple occurrences, all of them with different IDs
     * @type {string}
     * @memberof Node
     */
    originalId?: string;
    /**
     * 
     * @type {number}
     * @memberof Node
     */
    diagramId?: number;
    /**
     * 
     * @type {string}
     * @memberof Node
     */
    displayedName?: string;
    /**
     * 
     * @type {string}
     * @memberof Node
     */
    iri?: string;
    /**
     * 
     * @type {TypesEnum}
     * @memberof Node
     */
    type: TypesEnum;
    /**
     * 
     * @type {ElementAiGenerated}
     * @memberof Node
     */
    aiGenerated?: ElementAiGenerated;
    /**
     * 
     * @type {Position}
     * @memberof Node
     */
    position?: Position;
    /**
     * 
     * @type {Position}
     * @memberof Node
     */
    labelPosition?: Position;
    /**
     * 
     * @type {Position}
     * @memberof Node
     */
    geoPosition?: Position;
}

/**
 * Check if a given object implements the Node interface.
 */
export function instanceOfNode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function NodeFromJSON(json: any): Node {
    return NodeFromJSONTyped(json, false);
}

export function NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Node {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'originalId': !exists(json, 'originalId') ? undefined : json['originalId'],
        'diagramId': !exists(json, 'diagramId') ? undefined : json['diagramId'],
        'displayedName': !exists(json, 'displayedName') ? undefined : json['displayedName'],
        'iri': !exists(json, 'iri') ? undefined : json['iri'],
        'type': TypesEnumFromJSON(json['type']),
        'aiGenerated': !exists(json, 'ai_generated') ? undefined : ElementAiGeneratedFromJSON(json['ai_generated']),
        'position': !exists(json, 'position') ? undefined : PositionFromJSON(json['position']),
        'labelPosition': !exists(json, 'labelPosition') ? undefined : PositionFromJSON(json['labelPosition']),
        'geoPosition': !exists(json, 'geoPosition') ? undefined : PositionFromJSON(json['geoPosition']),
    };
}

export function NodeToJSON(value?: Node | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'originalId': value.originalId,
        'diagramId': value.diagramId,
        'displayedName': value.displayedName,
        'iri': value.iri,
        'type': TypesEnumToJSON(value.type),
        'ai_generated': ElementAiGeneratedToJSON(value.aiGenerated),
        'position': PositionToJSON(value.position),
        'labelPosition': PositionToJSON(value.labelPosition),
        'geoPosition': PositionToJSON(value.geoPosition),
    };
}

