/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SparqlingEntity } from './SparqlingEntity';
import {
    SparqlingEntityFromJSON,
    SparqlingEntityFromJSONTyped,
    SparqlingEntityToJSON,
} from './SparqlingEntity';

/**
 * 
 * @export
 * @interface OntologyPath
 */
export interface OntologyPath {
    /**
     * Starts with lastSelectedIRI and ends with clickedIRI. In between the nodes and edges traversed in the path (ISA edge are marked as ISA)
     * @type {Array<SparqlingEntity>}
     * @memberof OntologyPath
     */
    entities?: Array<SparqlingEntity>;
}

/**
 * Check if a given object implements the OntologyPath interface.
 */
export function instanceOfOntologyPath(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OntologyPathFromJSON(json: any): OntologyPath {
    return OntologyPathFromJSONTyped(json, false);
}

export function OntologyPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): OntologyPath {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entities': !exists(json, 'entities') ? undefined : ((json['entities'] as Array<any>).map(SparqlingEntityFromJSON)),
    };
}

export function OntologyPathToJSON(value?: OntologyPath | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entities': value.entities === undefined ? undefined : ((value.entities as Array<any>).map(SparqlingEntityToJSON)),
    };
}

