/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';

/**
 * 
 * @export
 * @interface Viewport
 */
export interface Viewport {
    /**
     * 
     * @type {Position}
     * @memberof Viewport
     */
    pan: Position;
    /**
     * 
     * @type {number}
     * @memberof Viewport
     */
    zoom: number;
}

/**
 * Check if a given object implements the Viewport interface.
 */
export function instanceOfViewport(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pan" in value;
    isInstance = isInstance && "zoom" in value;

    return isInstance;
}

export function ViewportFromJSON(json: any): Viewport {
    return ViewportFromJSONTyped(json, false);
}

export function ViewportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Viewport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pan': PositionFromJSON(json['pan']),
        'zoom': json['zoom'],
    };
}

export function ViewportToJSON(value?: Viewport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pan': PositionToJSON(value.pan),
        'zoom': value.zoom,
    };
}

