/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InstanceFilter } from './InstanceFilter';
import {
    InstanceFilterFromJSON,
    InstanceFilterFromJSONTyped,
    InstanceFilterToJSON,
} from './InstanceFilter';

/**
 * 
 * @export
 * @interface VKGCustomFilter
 */
export interface VKGCustomFilter {
    /**
     * 
     * @type {number}
     * @memberof VKGCustomFilter
     */
    active: VKGCustomFilterActiveEnum;
    /**
     * 
     * @type {Array<InstanceFilter>}
     * @memberof VKGCustomFilter
     */
    filters: Array<InstanceFilter>;
}

/**
* @export
* @enum {string}
*/
export enum VKGCustomFilterActiveEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


/**
 * Check if a given object implements the VKGCustomFilter interface.
 */
export function instanceOfVKGCustomFilter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "active" in value;
    isInstance = isInstance && "filters" in value;

    return isInstance;
}

export function VKGCustomFilterFromJSON(json: any): VKGCustomFilter {
    return VKGCustomFilterFromJSONTyped(json, false);
}

export function VKGCustomFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): VKGCustomFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': json['active'],
        'filters': ((json['filters'] as Array<any>).map(InstanceFilterFromJSON)),
    };
}

export function VKGCustomFilterToJSON(value?: VKGCustomFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'filters': ((value.filters as Array<any>).map(InstanceFilterToJSON)),
    };
}

