/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomNodeRendering } from './CustomNodeRendering';
import {
    CustomNodeRenderingFromJSON,
    CustomNodeRenderingFromJSONTyped,
    CustomNodeRenderingToJSON,
} from './CustomNodeRendering';
import type { RDFGraph } from './RDFGraph';
import {
    RDFGraphFromJSON,
    RDFGraphFromJSONTyped,
    RDFGraphToJSON,
} from './RDFGraph';
import type { VKGCustomFilter } from './VKGCustomFilter';
import {
    VKGCustomFilterFromJSON,
    VKGCustomFilterFromJSONTyped,
    VKGCustomFilterToJSON,
} from './VKGCustomFilter';

/**
 * 
 * @export
 * @interface VKGSnapshot
 */
export interface VKGSnapshot {
    /**
     * 
     * @type {string}
     * @memberof VKGSnapshot
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VKGSnapshot
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof VKGSnapshot
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof VKGSnapshot
     */
    lastModification: number;
    /**
     * 
     * @type {RDFGraph}
     * @memberof VKGSnapshot
     */
    rdfGraph: RDFGraph;
    /**
     * 
     * @type {{ [key: string]: CustomNodeRendering; }}
     * @memberof VKGSnapshot
     */
    customNodeRenderings?: { [key: string]: CustomNodeRendering; };
    /**
     * 
     * @type {{ [key: string]: VKGCustomFilter; }}
     * @memberof VKGSnapshot
     */
    customFilters?: { [key: string]: VKGCustomFilter; };
}

/**
 * Check if a given object implements the VKGSnapshot interface.
 */
export function instanceOfVKGSnapshot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "lastModification" in value;
    isInstance = isInstance && "rdfGraph" in value;

    return isInstance;
}

export function VKGSnapshotFromJSON(json: any): VKGSnapshot {
    return VKGSnapshotFromJSONTyped(json, false);
}

export function VKGSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): VKGSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'lastModification': json['lastModification'],
        'rdfGraph': RDFGraphFromJSON(json['rdfGraph']),
        'customNodeRenderings': !exists(json, 'customNodeRenderings') ? undefined : (mapValues(json['customNodeRenderings'], CustomNodeRenderingFromJSON)),
        'customFilters': !exists(json, 'customFilters') ? undefined : (mapValues(json['customFilters'], VKGCustomFilterFromJSON)),
    };
}

export function VKGSnapshotToJSON(value?: VKGSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'lastModification': value.lastModification,
        'rdfGraph': RDFGraphToJSON(value.rdfGraph),
        'customNodeRenderings': value.customNodeRenderings === undefined ? undefined : (mapValues(value.customNodeRenderings, CustomNodeRenderingToJSON)),
        'customFilters': value.customFilters === undefined ? undefined : (mapValues(value.customFilters, VKGCustomFilterToJSON)),
    };
}

