export enum WidgetEnum {
  DIAGRAM_SELECTOR = 'diagram-selector',
  ENTITY_DETAILS = 'details',
  ENTITY_SELECTOR = 'entity-selector',
  FILTERS = 'filters',
  FIT_BUTTON = 'fit-button',
  FULLSCREEN_BUTTON = 'fullscreen-button',
  ONTOLOGY_EXPLORER = 'ontology-explorer',
  ONTOLOGY_INFO = 'ontology-info',
  OWL_VISUALIZER = 'owl-visualizer',
  RENDERER_SELECTOR = 'renderer-selector',
  LAYOUT_SETTINGS = 'layout-settings',
  SETTINGS = 'settings',
  ZOOM_TOOLS = 'zoom-tools',
  INITIAL_RENDERER_SELECTOR = 'initial-renderer-selector',
}