export enum WidgetEnum {
  DIAGRAM_SELECTOR = 'diagram-selector',
  ENTITY_DETAILS = 'details',
  ENTITY_SELECTOR = 'entity-selector',
  FILTERS = 'filters',
  FIT_BUTTON = 'fit-button',
  FULLSCREEN_BUTTON = 'fullscreen-button',
  ONTOLOGY_EXPLORER = 'ontology-explorer',
  ONTOLOGY_INFO = 'ontology-info',
  OWL_VISUALIZER = 'owl-visualizer',
  RENDERER_SELECTOR = 'renderer-selector',
  LAYOUT_SETTINGS = 'layout-settings',
  SETTINGS = 'settings',
  ZOOM_TOOLS = 'zoom-tools',
  NEW_CLASS = 'new-class',
  NEW_DIAGRAM = 'new-diagram',
  NEW_DATAPROPERTY = 'new-dataproperty',
  NEW_OBJECTPROPERTY = 'new-objectproperty',
  INITIAL_RENDERER_SELECTOR = 'initial-renderer-selector',
  /** @internal */
  CLASS_INSTANCE_DETAILS = 'class-instance-details',
  /** @internal */
  INSTANCES_EXPLORER = 'instances-explorer',
  /** @internal */
  NAVIGATION_MENU = 'naviagtion-menu',
  /** @internal */
  VKG_PREFERENCES = 'vkg-preferences',
  INCREMENTAL_INITIAL_MENU = 'incremental-initial-menu',
}