/* tslint:disable */
/* eslint-disable */
/**
 * VKG API model
 * This is the API for managing virtual knowledge graphs VKGs. VKGs are  crwated by exploring the data through the interface and then saved through this API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomNodeRendering,
} from '../models';
import {
    CustomNodeRenderingFromJSON,
    CustomNodeRenderingToJSON,
} from '../models';

export interface DeleteVkgNodeRenderingRequest {
    name: string;
    version: string;
}

export interface GetDefaultNodeRenderingRequest {
    name: string;
    version: string;
}

export interface PostDefaultNodeRenderingRequest {
    name: string;
    version: string;
    requestBody: { [key: string]: CustomNodeRendering; };
}

export interface PutDefaultNodeRenderingRequest {
    name: string;
    version: string;
    requestBody: { [key: string]: CustomNodeRendering; };
}

/**
 * 
 */
export class NodeRenderingApi extends runtime.BaseAPI {

    /**
     * DELETE mwsx/owlOntology/{name}/version/vkg/node-rendering
     */
    async deleteVkgNodeRenderingRaw(requestParameters: DeleteVkgNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling deleteVkgNodeRendering.');
        }

        if (requestParameters.version === null || requestParameters.version === undefined) {
            throw new runtime.RequiredError('version','Required parameter requestParameters.version was null or undefined when calling deleteVkgNodeRendering.');
        }

        const queryParameters: any = {};

        if (requestParameters.version !== undefined) {
            queryParameters['version'] = requestParameters.version;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-MONOLITH-SESSION-ID"] = this.configuration.apiKey("X-MONOLITH-SESSION-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/owlOntology/{name}/version/vkg/node-rendering`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * DELETE mwsx/owlOntology/{name}/version/vkg/node-rendering
     */
    async deleteVkgNodeRendering(requestParameters: DeleteVkgNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVkgNodeRenderingRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the default VKG node rendering for the ontology version
     */
    async getDefaultNodeRenderingRaw(requestParameters: GetDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: CustomNodeRendering; }>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling getDefaultNodeRendering.');
        }

        if (requestParameters.version === null || requestParameters.version === undefined) {
            throw new runtime.RequiredError('version','Required parameter requestParameters.version was null or undefined when calling getDefaultNodeRendering.');
        }

        const queryParameters: any = {};

        if (requestParameters.version !== undefined) {
            queryParameters['version'] = requestParameters.version;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-MONOLITH-SESSION-ID"] = this.configuration.apiKey("X-MONOLITH-SESSION-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/owlOntology/{name}/version/vkg/node-rendering`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, CustomNodeRenderingFromJSON));
    }

    /**
     * Returns the default VKG node rendering for the ontology version
     */
    async getDefaultNodeRendering(requestParameters: GetDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: CustomNodeRendering; }> {
        const response = await this.getDefaultNodeRenderingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set a default VKG node rendering for the ontology version
     */
    async postDefaultNodeRenderingRaw(requestParameters: PostDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: CustomNodeRendering; }>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling postDefaultNodeRendering.');
        }

        if (requestParameters.version === null || requestParameters.version === undefined) {
            throw new runtime.RequiredError('version','Required parameter requestParameters.version was null or undefined when calling postDefaultNodeRendering.');
        }

        if (requestParameters.requestBody === null || requestParameters.requestBody === undefined) {
            throw new runtime.RequiredError('requestBody','Required parameter requestParameters.requestBody was null or undefined when calling postDefaultNodeRendering.');
        }

        const queryParameters: any = {};

        if (requestParameters.version !== undefined) {
            queryParameters['version'] = requestParameters.version;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-MONOLITH-SESSION-ID"] = this.configuration.apiKey("X-MONOLITH-SESSION-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/owlOntology/{name}/version/vkg/node-rendering`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, CustomNodeRenderingFromJSON));
    }

    /**
     * Set a default VKG node rendering for the ontology version
     */
    async postDefaultNodeRendering(requestParameters: PostDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: CustomNodeRendering; }> {
        const response = await this.postDefaultNodeRenderingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Modifies the default VKG node rendering for the ontology version
     */
    async putDefaultNodeRenderingRaw(requestParameters: PutDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: CustomNodeRendering; }>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling putDefaultNodeRendering.');
        }

        if (requestParameters.version === null || requestParameters.version === undefined) {
            throw new runtime.RequiredError('version','Required parameter requestParameters.version was null or undefined when calling putDefaultNodeRendering.');
        }

        if (requestParameters.requestBody === null || requestParameters.requestBody === undefined) {
            throw new runtime.RequiredError('requestBody','Required parameter requestParameters.requestBody was null or undefined when calling putDefaultNodeRendering.');
        }

        const queryParameters: any = {};

        if (requestParameters.version !== undefined) {
            queryParameters['version'] = requestParameters.version;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-MONOLITH-SESSION-ID"] = this.configuration.apiKey("X-MONOLITH-SESSION-ID"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/owlOntology/{name}/version/vkg/node-rendering`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, CustomNodeRenderingFromJSON));
    }

    /**
     * Modifies the default VKG node rendering for the ontology version
     */
    async putDefaultNodeRendering(requestParameters: PutDefaultNodeRenderingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: CustomNodeRendering; }> {
        const response = await this.putDefaultNodeRenderingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
