/* tslint:disable */
/* eslint-disable */
/**
 * Grapholscape API model
 * This is the API for retaining a Grapholscape\'s loaded ontology (or graph) in order to restart navigation from a previous state.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: obdasystems@info.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InstanceShortestPathInput,
} from '../models';
import {
    InstanceShortestPathInputFromJSON,
    InstanceShortestPathInputToJSON,
} from '../models';

export interface InstanceShortestPathPostRequest {
    instanceShortestPathInput: InstanceShortestPathInput;
}

/**
 * 
 */
export class VKGApi extends runtime.BaseAPI {

    /**
     * Return the CONSTRUCT query based on the shortest path between an instance and another instance or class
     */
    async instanceShortestPathPostRaw(requestParameters: InstanceShortestPathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.instanceShortestPathInput === null || requestParameters.instanceShortestPathInput === undefined) {
            throw new runtime.RequiredError('instanceShortestPathInput','Required parameter requestParameters.instanceShortestPathInput was null or undefined when calling instanceShortestPathPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/instanceShortestPath`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InstanceShortestPathInputToJSON(requestParameters.instanceShortestPathInput),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Return the CONSTRUCT query based on the shortest path between an instance and another instance or class
     */
    async instanceShortestPathPost(requestParameters: InstanceShortestPathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.instanceShortestPathPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
